# Generated by Django 6.0.7 on 2026-08-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_websitepopup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitepopup',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
