# Generated by Django 6.0.7 on 2026-08-08 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_websitepopup_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Login account this customer can use to view their portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer this support ticket belongs to, when created from the customer portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='myapp.customer'),
        ),
    ]
