# Generated by Django 6.0.7 on 2026-08-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_customer_user_ticket_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customer',
        ),
    ]
