# Generated by Django 6.0.7 on 2026-08-08 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_customer_user_ticket_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EBankingCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('temporary_password', models.CharField(blank=True, help_text='Shown for admin handover. Cleared when the customer changes their password.', max_length=128)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ebanking_credential', to='myapp.customer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ebanking_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'E-Banking',
                'verbose_name_plural': 'E-Banking',
                'ordering': ['customer__customer_id'],
            },
        ),
    ]
