# Generated by Django 6.0.7 on 2026-08-09 05:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrecord',
            name='collected_at_was_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='datetime_approval_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='datetime_approval_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='datetime_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='datetime_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_collection_datetimes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='collected_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
