# Generated by Django 6.0.7 on 2026-08-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_collectionrecord_collected_at_was_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrecord',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='payment_receipt',
            field=models.FileField(blank=True, upload_to='payment_receipts/'),
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_receipt',
            field=models.FileField(blank=True, upload_to='payment_receipts/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
