# Generated by Django 6.0.7 on 2026-08-09 07:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_loanapplication_loanrepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deposit_type', models.CharField(choices=[('fixed', 'Fixed Deposit'), ('recurring', 'Recurring Deposit')], default='fixed', max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tenure_months', models.PositiveIntegerField(default=12)),
                ('interest_payout', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('maturity', 'On Maturity')], default='maturity', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('matured', 'Matured'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('nominee_name', models.CharField(blank=True, max_length=160)),
                ('nominee_phone', models.CharField(blank=True, max_length=30)),
                ('certificate_file', models.FileField(blank=True, upload_to='deposit_certificates/')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_reason', models.CharField(blank=True, max_length=220)),
                ('remarks', models.CharField(blank=True, max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deposits', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_accounts', to='myapp.customer')),
            ],
            options={
                'verbose_name': 'Fixed / Recurring Deposit',
                'verbose_name_plural': 'Fixed / Recurring Deposits',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DepositPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('payment_receipt', models.FileField(blank=True, upload_to='deposit_payment_receipts/')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_payments_collected', to=settings.AUTH_USER_MODEL)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='myapp.depositaccount')),
            ],
            options={
                'verbose_name': 'Deposit Payment',
                'verbose_name_plural': 'Deposit Payments',
                'ordering': ['-paid_at', '-id'],
            },
        ),
    ]
