# Generated by Django 6.0.7 on 2026-08-09 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_securityevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Nanu Investment Pvt. Ltd.', max_length=180)),
                ('company_address', models.CharField(default='Barahathawa-12, Sarlahi, Nepal', max_length=220)),
                ('company_phone', models.CharField(default='+977 9744360267', max_length=40)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('pan_vat_number', models.CharField(blank=True, max_length=80)),
                ('company_logo', models.FileField(blank=True, upload_to='system/')),
                ('favicon', models.FileField(blank=True, upload_to='system/')),
                ('receipt_prefix', models.CharField(default='TXN', max_length=12)),
                ('date_format', models.CharField(default='d M Y, H:i', max_length=40)),
                ('currency_label', models.CharField(default='Rs', max_length=12)),
                ('customer_signature_label', models.CharField(default='Customer Signature', max_length=80)),
                ('authorized_signature_label', models.CharField(default='Authorized Signature', max_length=80)),
                ('default_payment_method', models.CharField(default='Cash', max_length=40)),
                ('receipt_footer_text', models.CharField(default='This bill was generated by Nanu Investment transaction system.', max_length=250)),
                ('default_saving_interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('default_loan_interest_rate', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('default_fixed_deposit_rate', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('default_recurring_deposit_rate', models.DecimalField(decimal_places=2, default=7, max_digits=5)),
                ('penalty_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grace_period_days', models.PositiveIntegerField(default=0)),
                ('require_manual_collection_datetime_approval', models.BooleanField(default=True)),
                ('require_loan_approval', models.BooleanField(default=True)),
                ('require_deposit_approval', models.BooleanField(default=True)),
                ('approval_threshold_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('failed_login_alert_threshold', models.PositiveIntegerField(default=5)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=120)),
                ('password_policy_note', models.CharField(default='Use a strong password and do not share credentials.', max_length=220)),
                ('allow_staff_profile_uploads', models.BooleanField(default=True)),
                ('sms_sender_name', models.CharField(blank=True, max_length=80)),
                ('email_sender', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_template', models.TextField(blank=True)),
                ('sms_receipt_template', models.TextField(blank=True)),
                ('email_receipt_template', models.TextField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('backup_note', models.CharField(blank=True, max_length=220)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_system_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
