# Generated by Django 6.0.7 on 2026-08-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_systemsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebankingcredential',
            name='temporary_password',
            field=models.CharField(blank=True, help_text='Raw temporary passwords are shown once during handover and are not stored.', max_length=128),
        ),
    ]
