# Generated by Django 6.0.7 on 2026-08-09 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_ebankingcredential_temporary_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='sms_receipt_template',
            field=models.TextField(blank=True, help_text='Optional collection SMS template. Available fields: {company_name}, {customer_name}, {customer_id}, {currency}, {amount}, {receipt}, {balance}, {date}, {payment_method}.'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='sms_sender_name',
            field=models.CharField(blank=True, help_text='Name shown at the start of SMS messages. The AakashSMS account controls the network Sender ID.', max_length=80),
        ),
        migrations.CreateModel(
            name='SMSDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('collection_receipt', 'Collection Receipt')], default='collection_receipt', max_length=40)),
                ('provider', models.CharField(default='AakashSMS', max_length=40)),
                ('recipient', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued by AakashSMS'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=80)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_deliveries', to='myapp.customer')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_delivery', to='myapp.transaction')),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
                'ordering': ('-created_at',),
            },
        ),
    ]
