# Generated by Django 6.0.7 on 2026-08-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_systemsetting_sms_receipt_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdelivery',
            name='event_type',
            field=models.CharField(choices=[('collection_receipt', 'Collection Receipt'), ('ebanking_login', 'E-Banking Login')], default='collection_receipt', max_length=40),
        ),
    ]
