# Generated by Django 6.0.7 on 2026-08-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_smsdelivery_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdelivery',
            name='event_type',
            field=models.CharField(choices=[('collection_receipt', 'Collection Receipt'), ('ebanking_login', 'E-Banking Login'), ('temporary_password', 'Temporary Password')], default='collection_receipt', max_length=40),
        ),
    ]
